{
    "openapi": "3.0.1",
    "info": {
      "title": "Audio Services: Enhance Speech API",
      "version": "v2"
    },
    "paths": {
      "/v2/assets": {
        "post": {
          "summary": "Create an asset",
          "tags": [
            "Assets"
          ],
          "description": "Create an asset. You will receive an `uploadUrl` in the response, which you can use to upload the asset.",
          "operationId": "createAsset",
          "parameters": [

          ],
          "security": [
            {
              "bearer_auth": [

              ],
              "api_key": [

              ]
            }
          ],
          "responses": {
            "401": {
              "description": "Unauthorized",
              "content": {
                "application/json": {
                  "examples": {
                    "access_token_invalid": {
                      "value": {
                        "error_code": "401013",
                        "message": "Oauth token is not valid"
                      },
                      "summary": "Access token is not valid"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "403": {
              "description": "Forbidden",
              "content": {
                "application/json": {
                  "examples": {
                    "access_token_lacks_proper_scope": {
                      "value": {
                        "error_code": null,
                        "message": "Missing required scope"
                      },
                      "summary": "Access token lacks the proper scope"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "429": {
              "description": "Too Many Requests",
              "content": {
                "application/json": {
                  "examples": {
                    "too_many_requests": {
                      "value": {
                        "error_code": "429050",
                        "message": "Too many requests"
                      },
                      "summary": "Client has made too many requests"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "201": {
              "description": "Asset created",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/asset"
                  }
                }
              }
            },
            "422": {
              "description": "Request missing required parameter fileName",
              "content": {
                "application/json": {
                  "examples": {
                    "request_missing_required_parameter": {
                      "value": {
                        "error_code": null,
                        "message": "#/paths/~1v2~1assets/post/requestBody/content/application~1json/schema missing required parameters: fileName"
                      },
                      "summary": "Request missing a required parameter"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            }
          },
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "fileName": {
                      "type": "string",
                      "description": "Name of the uploaded file (including file extension)."
                    },
                    "byteSize": {
                      "type": "integer",
                      "description": "Number of bytes of the file. Must match the value of the `Content-Length` header when uploading directly to S3."
                    },
                    "mediaType": {
                      "type": "string",
                      "description": "Content type of the file. Must match the value of `Content-Type` header when uploading directly to S3.",
                      "enum": [
                        "audio/aac",
                        "audio/flac",
                        "audio/m4a",
                        "audio/mp4",
                        "audio/mpeg",
                        "audio/mpeg4-generic",
                        "audio/ogg",
                        "audio/opus",
                        "audio/vnd.dlna.adts",
                        "audio/vorbis",
                        "audio/wav",
                        "audio/x-aac",
                        "audio/x-aiff",
                        "audio/x-flac",
                        "audio/x-m4a",
                        "audio/x-wav"
                      ]
                    }
                  },
                  "required": [
                    "fileName",
                    "byteSize",
                    "mediaType"
                  ]
                },
                "examples": {
                  "name": {
                    "summary": "summary",
                    "value": {
                      "fileName": "audio-file.mp3",
                      "byteSize": 31005,
                      "mediaType": "audio/mpeg"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "servers": [
      {
        "url": "https://firefly-api-enterprise-stage.adobe.io/audio_services"
      }
    ],
    "components": {
      "securitySchemes": {
        "bearer_auth": {
          "type": "http",
          "scheme": "bearer"
        },
        "api_key": {
          "type": "apiKey",
          "in": "header",
          "name": "X-Api-Key"
        }
      },
      "schemas": {
        "asset": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "nullable": false,
              "format": "uuid",
              "example": "bcab9f0c-f740-41f1-990e-c21f2cae6af0",
              "description": "Unique ID of the asset."
            },
            "fileName": {
              "type": "string",
              "nullable": false,
              "example": "audio-file.mp3",
              "description": "Name of uploaded file (including file extension)."
            },
            "uploadUrl": {
              "type": "string",
              "nullable": true,
              "example": "https://bucket.s3-accelerate.amazonaws.com/Assets/...",
              "description": "Pre-signed S3 URL to upload file to. Expires after 5 minutes. See guide and S3 [`PutObject` docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html)"
            },
            "status": {
              "type": "string",
              "nullable": false,
              "enum": [
                "waiting_for_upload",
                "ready_for_processing",
                "invalid_upload"
              ],
              "example": "waiting_for_upload",
              "description": "Indicates the upload status of the Asset. The original status is `waiting_for_upload` and, after successfully being uploaded to S3, is `ready_for_processing`. An asset is `upload_invalid` if the underlying file is deemed unacceptable."
            },
            "byteSize": {
              "type": "integer",
              "nullable": true,
              "minimum": 0,
              "example": 31005,
              "description": "Number of bytes of the file."
            },
            "mediaType": {
              "type": "string",
              "nullable": true,
              "example": "audio/mpeg",
              "description": "Media type of the file."
            },
            "checksum": {
              "type": "string",
              "nullable": true,
              "example": "6gH7SfirkyEWPA+QeOuJjQ==",
              "description": "Base64 encoded MD5 checksum of the uploaded file."
            },
            "updatedAt": {
              "type": "string",
              "nullable": false,
              "format": "date-time",
              "description": "Datetime of when the asset was last updated."
            },
            "createdAt": {
              "type": "string",
              "nullable": false,
              "format": "date-time",
              "description": "Datetime of when the asset was created."
            }
          },
          "required": [
            "id",
            "fileName",
            "uploadUrl",
            "status",
            "byteSize",
            "mediaType",
            "checksum",
            "updatedAt",
            "createdAt"
          ]
        },
        "error": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string",
              "nullable": false
            },
            "error_code": {
              "type": "string",
              "nullable": true
            }
          },
          "required": [
            "message",
            "error_code"
          ]
        }
      }
    }
  }