{
    "openapi": "3.0.1",
    "info": {
      "title": "Audio Services: Enhance Speech API",
      "version": "v2"
    },
    "paths": {
      "/v2/speech-enhancements/{id}": {
        "get": {
          "summary": "Get a speech enhancement",
          "description": "Retrieve information about a speech enhancement for an asset, identified by `id`. This endpoint allows you to view the details of a speech enhancement that was previously created using the `POST /v2/speech-enhancements` endpoint.",
          "operationId": "getSpeechEnhancement",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "required": true,
              "description": "ID of the desired speech enhancement.",
              "schema": {
                "type": "string"
              }
            }
          ],
          "security": [
            {
              "bearer_auth": [

              ],
              "api_key": [

              ]
            }
          ],
          "responses": {
            "401": {
              "description": "Unauthorized",
              "content": {
                "application/json": {
                  "examples": {
                    "access_token_invalid": {
                      "value": {
                        "error_code": "401013",
                        "message": "Oauth token is not valid"
                      },
                      "summary": "Access token is not valid"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "403": {
              "description": "Forbidden",
              "content": {
                "application/json": {
                  "examples": {
                    "access_token_lacks_proper_scope": {
                      "value": {
                        "error_code": null,
                        "message": "Missing required scope"
                      },
                      "summary": "Access token lacks the proper scope"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "429": {
              "description": "Too Many Requests",
              "content": {
                "application/json": {
                  "examples": {
                    "too_many_requests": {
                      "value": {
                        "error_code": "429050",
                        "message": "Too many requests"
                      },
                      "summary": "Client has made too many requests"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "200": {
              "description": "Speech enhancement found",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/speech_enhancement"
                  }
                }
              }
            },
            "404": {
              "description": "Speech enhancement not found",
              "content": {
                "application/json": {
                  "examples": {
                    "speech_enhancement_not_found": {
                      "value": {
                        "error_code": null,
                        "message": "Not found"
                      },
                      "summary": "Speech enhancement not found"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "servers": [
      {
        "url": "https://firefly-api-enterprise-stage.adobe.io/audio_services"
      }
    ],
    "components": {
      "securitySchemes": {
        "bearer_auth": {
          "type": "http",
          "scheme": "bearer"
        },
        "api_key": {
          "type": "apiKey",
          "in": "header",
          "name": "X-Api-Key"
        }
      },
      "schemas": {
        "error": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string",
              "nullable": false
            },
            "error_code": {
              "type": "string",
              "nullable": true
            }
          },
          "required": [
            "message",
            "error_code"
          ]
        },
        "speech_enhancement": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "nullable": false,
              "format": "uuid",
              "example": "d7748c6d-4be9-41e7-a6a8-d4138eaa8219",
              "description": "Unique ID of the speech enhancement."
            },
            "strength": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100,
              "nullable": false,
              "example": 90,
              "description": "Percentage strength of speech enhancement."
            },
            "modelId": {
              "type": "string",
              "nullable": false,
              "example": "v1",
              "description": "Unique identifier of the model that performs speech enhancement."
            },
            "assetId": {
              "type": "string",
              "nullable": false,
              "format": "uuid",
              "example": "bcab9f0c-f740-41f1-990e-c21f2cae6af0",
              "description": "Unique ID of the asset of the speech enhancement."
            },
            "requestedProcessingAt": {
              "type": "string",
              "format": "date-time",
              "nullable": false,
              "description": "Datetime of when the speech enhancement was created."
            },
            "finishedProcessingAt": {
              "type": "string",
              "format": "date-time",
              "nullable": true,
              "description": "Datetime of when the speech enhancement was completed."
            },
            "status": {
              "type": "string",
              "enum": [
                "failed",
                "succeeded",
                "processing",
                "queued"
              ],
              "nullable": false,
              "example": "processing",
              "description": "Indicates the processing status of the speech enhancement."
            },
            "output": {
              "type": "object",
              "nullable": true,
              "properties": {
                "url": {
                  "type": "string",
                  "nullable": true,
                  "example": "https://bucket.s3-accelerate.amazonaws.com/Assets/...",
                  "description": "URL that provides access to download the speech enhancement as a file. Only available when the status is `succeeded`."
                }
              }
            }
          },
          "required": [
            "id",
            "strength",
            "modelId",
            "assetId",
            "requestedProcessingAt",
            "finishedProcessingAt",
            "status",
            "output"
          ]
        }
      }
    }
  }