{
    "openapi": "3.0.1",
    "info": {
      "title": "Audio Services: Enhance Speech API",
      "version": "v2"
    },
    "paths": {
      "/v2/assets/{id}": {
        "delete": {
          "summary": "Delete an asset",
          "description": "Delete the asset with the specified `id`.",
          "operationId": "deleteAsset",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "required": true,
              "description": "ID of the desired asset.",
              "schema": {
                "type": "string"
              }
            }
          ],
          "security": [
            {
              "bearer_auth": [

              ],
              "api_key": [

              ]
            }
          ],
          "responses": {
            "404": {
              "description": "Asset does not exist",
              "content": {
                "application/json": {
                  "examples": {
                    "asset_not_found": {
                      "value": {
                        "error_code": null,
                        "message": "Not found"
                      },
                      "summary": "Asset not found"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized",
              "content": {
                "application/json": {
                  "examples": {
                    "access_token_invalid": {
                      "value": {
                        "error_code": "401013",
                        "message": "Oauth token is not valid"
                      },
                      "summary": "Access token is not valid"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "403": {
              "description": "Forbidden",
              "content": {
                "application/json": {
                  "examples": {
                    "access_token_lacks_proper_scope": {
                      "value": {
                        "error_code": null,
                        "message": "Missing required scope"
                      },
                      "summary": "Access token lacks the proper scope"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "429": {
              "description": "Too Many Requests",
              "content": {
                "application/json": {
                  "examples": {
                    "too_many_requests": {
                      "value": {
                        "error_code": "429050",
                        "message": "Too many requests"
                      },
                      "summary": "Client has made too many requests"
                    }
                  },
                  "schema": {
                    "$ref": "#/components/schemas/error"
                  }
                }
              }
            },
            "204": {
              "description": "Asset deleted",
              "content": {
                "application/json": {
                  "examples": {
                    "asset_deleted": {
                      "summary": "Asset and any speech enhancements successfully deleted"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "servers": [
      {
        "url": "https://audio-services-stage.adobe.io/api"
      }
    ],
    "components": {
      "securitySchemes": {
        "bearer_auth": {
          "type": "http",
          "scheme": "bearer"
        },
        "api_key": {
          "type": "apiKey",
          "in": "header",
          "name": "X-Api-Key"
        }
      },
      "schemas": {
        "asset": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "nullable": false,
              "format": "uuid",
              "example": "bcab9f0c-f740-41f1-990e-c21f2cae6af0",
              "description": "Unique ID of the asset."
            },
            "fileName": {
              "type": "string",
              "nullable": false,
              "example": "audio-file.mp3",
              "description": "Name of uploaded file (including file extension)."
            },
            "uploadUrl": {
              "type": "string",
              "nullable": true,
              "example": "https://bucket.s3-accelerate.amazonaws.com/Assets/...",
              "description": "Pre-signed S3 URL to upload file to. Expires after 5 minutes. See guide and S3 [`PutObject` docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html)"
            },
            "status": {
              "type": "string",
              "nullable": false,
              "enum": [
                "waiting_for_upload",
                "ready_for_processing",
                "invalid_upload"
              ],
              "example": "waiting_for_upload",
              "description": "Indicates the upload status of the Asset. The original status is `waiting_for_upload` and, after successfully being uploaded to S3, is `ready_for_processing`. An asset is `upload_invalid` if the underlying file is deemed unacceptable."
            },
            "byteSize": {
              "type": "integer",
              "nullable": true,
              "minimum": 0,
              "example": 31005,
              "description": "Number of bytes of the file."
            },
            "mediaType": {
              "type": "string",
              "nullable": true,
              "example": "audio/mpeg",
              "description": "Media type of the file."
            },
            "checksum": {
              "type": "string",
              "nullable": true,
              "example": "6gH7SfirkyEWPA+QeOuJjQ==",
              "description": "Base64 encoded MD5 checksum of the uploaded file."
            },
            "updatedAt": {
              "type": "string",
              "nullable": false,
              "format": "date-time",
              "description": "Datetime of when the asset was last updated."
            },
            "createdAt": {
              "type": "string",
              "nullable": false,
              "format": "date-time",
              "description": "Datetime of when the asset was created."
            }
          },
          "required": [
            "id",
            "fileName",
            "uploadUrl",
            "status",
            "byteSize",
            "mediaType",
            "checksum",
            "updatedAt",
            "createdAt"
          ]
        },
        "error": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string",
              "nullable": false
            },
            "error_code": {
              "type": "string",
              "nullable": true
            }
          },
          "required": [
            "message",
            "error_code"
          ]
        }
      }
    }
  }
